name: PHP Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  php_checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ps_sovendus

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.1"
          tools: composer, phpcs, phpstan
          coverage: none

      - name: PHP Syntax Check
        run: find . -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 php -l

      - name: Install PHP_CodeSniffer dependencies
        run: composer global require "phpcompatibility/php-compatibility"

      - name: PHP CodeSniffer Check
        run: phpcs --standard=phpcs.xml -p

      - name: Static Analysis
        run: phpstan analyse --no-progress
